import type { Locale } from "@/i18n/config";

type BreedMap = Record<Locale, string[]>;

export const DOG_BREEDS: BreedMap = {
  en: [
    "Labrador Retriever",
    "Golden Retriever",
    "German Shepherd",
    "French Bulldog",
    "Bulldog",
    "Poodle",
    "Beagle",
    "Rottweiler",
    "Dachshund",
    "Yorkshire Terrier",
    "Boxer",
    "Siberian Husky",
    "Great Dane",
    "Doberman Pinscher",
    "Australian Shepherd",
    "Shih Tzu",
    "Border Collie",
    "Chihuahua",
    "Bernese Mountain Dog",
    "Cavalier King Charles Spaniel",
    "Pembroke Welsh Corgi",
    "Miniature Schnauzer",
    "Shiba Inu",
    "Cocker Spaniel",
    "Pomeranian",
    "Basset Hound",
    "Jack Russell Terrier",
    "Pug",
    "Weimaraner",
    "Vizsla",
    "Saint Bernard",
    "Newfoundland",
    "Dalmatian",
    "Samoyed",
    "Akita",
    "Mixed Breed",
  ],
  nl: [
    "Labrador Retriever",
    "Golden Retriever",
    "Duitse Herder",
    "Franse Bulldog",
    "Engelse Bulldog",
    "Poedel",
    "Beagle",
    "Rottweiler",
    "Teckel",
    "Yorkshire Terriër",
    "Boxer",
    "Siberische Husky",
    "Deense Dog",
    "Dobermann",
    "Australische Herder",
    "Shih Tzu",
    "Border Collie",
    "Chihuahua",
    "Berner Sennenhond",
    "Cavalier King Charles Spaniël",
    "Welsh Corgi Pembroke",
    "Dwergschnauzer",
    "Shiba Inu",
    "Cocker Spaniël",
    "Pomeriaan",
    "Basset Hound",
    "Jack Russell Terriër",
    "Mopshond",
    "Weimaraner",
    "Vizsla",
    "Sint-Bernard",
    "Newfoundlander",
    "Dalmatiër",
    "Samojeed",
    "Akita",
    "Kruising",
  ],
  ro: [
    "Labrador Retriever",
    "Golden Retriever",
    "Ciobanesc German",
    "Buldog Francez",
    "Buldog Englez",
    "Pudel",
    "Beagle",
    "Rottweiler",
    "Teckel",
    "Yorkshire Terrier",
    "Boxer",
    "Husky Siberian",
    "Dog German",
    "Doberman",
    "Ciobanesc Australian",
    "Shih Tzu",
    "Border Collie",
    "Chihuahua",
    "Ciobanesc de Berna",
    "Cavalier King Charles Spaniel",
    "Welsh Corgi Pembroke",
    "Schnauzer Pitic",
    "Shiba Inu",
    "Cocker Spaniel",
    "Pomeranian",
    "Basset Hound",
    "Jack Russell Terrier",
    "Mops",
    "Weimaraner",
    "Vizsla",
    "Saint Bernard",
    "Newfoundland",
    "Dalmatian",
    "Samoyed",
    "Akita",
    "Metis",
  ],
};

export const CAT_BREEDS: BreedMap = {
  en: [
    "Domestic Shorthair",
    "Domestic Longhair",
    "Maine Coon",
    "Persian",
    "Ragdoll",
    "British Shorthair",
    "Siamese",
    "Bengal",
    "Sphynx",
    "Scottish Fold",
    "Russian Blue",
    "Abyssinian",
    "American Shorthair",
    "Norwegian Forest Cat",
    "Birman",
    "Oriental Shorthair",
    "Devon Rex",
    "Cornish Rex",
    "Burmese",
    "Himalayan",
    "Turkish Angora",
    "Savannah",
    "Tonkinese",
    "Exotic Shorthair",
    "Ragamuffin",
    "Chartreux",
    "Manx",
    "Somali",
    "Egyptian Mau",
    "Mixed Breed",
  ],
  nl: [
    "Europese Korthaar",
    "Europese Langhaar",
    "Maine Coon",
    "Perzische Kat",
    "Ragdoll",
    "Britse Korthaar",
    "Siamees",
    "Bengaal",
    "Sphynx",
    "Scottish Fold",
    "Russisch Blauw",
    "Abessijn",
    "Amerikaanse Korthaar",
    "Noorse Boskat",
    "Heilige Birmaan",
    "Oriëntaal Korthaar",
    "Devon Rex",
    "Cornish Rex",
    "Birmaan",
    "Himalayaan",
    "Turkse Angora",
    "Savannah",
    "Tonkinees",
    "Exotic Shorthair",
    "Ragamuffin",
    "Chartreux",
    "Manx",
    "Somali",
    "Egyptische Mau",
    "Kruising",
  ],
  ro: [
    "Pisica de Casa (par scurt)",
    "Pisica de Casa (par lung)",
    "Maine Coon",
    "Persana",
    "Ragdoll",
    "British Shorthair",
    "Siameza",
    "Bengaleza",
    "Sphynx",
    "Scottish Fold",
    "Albastru de Rusia",
    "Abisiniana",
    "American Shorthair",
    "Pisica de Padure Norvegiana",
    "Birmaneza Sacra",
    "Orientala cu Par Scurt",
    "Devon Rex",
    "Cornish Rex",
    "Burmeza",
    "Himalayana",
    "Angora Turceasca",
    "Savannah",
    "Tonkineza",
    "Exotic Shorthair",
    "Ragamuffin",
    "Chartreux",
    "Manx",
    "Somali",
    "Mau Egiptean",
    "Metis",
  ],
};

export function getBreedsFor(
  species: "dog" | "cat" | "horse" | "other" | null,
  locale: Locale
): string[] {
  if (species === "dog") return DOG_BREEDS[locale] ?? DOG_BREEDS.en;
  if (species === "cat") return CAT_BREEDS[locale] ?? CAT_BREEDS.en;
  return [];
}
